version: '3.8'
services:
  flask-app:
    build:
      context: .  
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
      - flask_db_data:/app/db  
    environment:
      FLASK_APP: run.py  
      FLASK_RUN_HOST: 0.0.0.0  
      FLASK_ENV: development  

volumes:
  flask_db_data:
    driver: local  
